{
 "title": "Air Quality [Awair]",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sensor_id",
    "query": "label_values(awair_sensor_score, sensor_id)"
   }
  ]
 },
 "panels": [
  { "title": "Awair #$sensor_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "sensor_id" },
  {
   "title": "Score",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(avg_over_time(awair_sensor_score[$__interval])) by (sensor_id)"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(avg_over_time(awair_sensor_co2[$__interval])) by (sensor_id)"
    }
   ]
  },
  {
   "title": "VOC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(avg_over_time(awair_sensor_voc[$__interval])) by (sensor_id)"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(avg_over_time(awair_sensor_humid[$__interval])) by (sensor_id)"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(avg_over_time(awair_sensor_temp[$__interval])) by (sensor_id)"
    }
   ]
  },
  {
   "title": "pm25",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(avg_over_time(awair_sensor_pm25[$__interval])) by (sensor_id)"
    }
   ]
  }
 ]
}